services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - "db"
    networks:
      - ev_charger_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - ev_charger_network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: -p 5433
    ports:
      - "5433:5433"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev_charger_network

networks:
  ev_charger_network:
    driver: bridge
    name: ev_charger_network

volumes:
  postgres_data:
  frontend_node_modules:
  frontend_next:
