FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml .
COPY app app/
COPY packages packages/

RUN uv venv
RUN uv pip install -e .

CMD ["uv", "run", "api"]